package il.co.ilrd.sunhttpserver;

public enum DatabaseKeys {
	CREATE_COMPANY_DATABASE,
	CREATE_TABLE,
	DELETE_TABLE,
	CREATE_IOT_EVENT,
	CREATE_ROW,
	READ_ROW,
	READ_FIELD_BY_NAME,
	READ_FIELD_BY_INDEX,
	UPDATE_FIELD_BY_NAME,
	UPDATE_FIELD_BY_INDEX,
	DELETE_ROW,
	ERROR_MESSAGE,
	ACK_MESSAGE;
}
